server:
  port: 8080
  hostnames: ""
  session:
    token:
      secret: ""

hls:
  origin-base-url: http://127.0.0.1/hls
  ad-base-url: http://127.0.0.1/ads
  ad-frequency-minutes: 2
  segment-duration-seconds: 5
  output-path: /Users/amalkabulov/IdeaProjects/zeno/nginx-hls-voulume/hls

service:
  load-balancer:
    url: ${LOAD_BALANCER_SERVICE_URL:https://stream-dev.zeno.fm}
  #    load-balancer: "http://localhost:8080"
  stream-base:
    url: ${STREAM_BASE_URL:https://upstream-dev.zenomedia.com}
  elasticsearch:
    ads:
      url: ${ES_ADS_URL:https://ads-es.zenomedia.com:443}
      index: ${ES_ADS_INDEX:dev-ad-events*}
    sessions:
      url: ${ES_SESSIONS_URL:https://streaming-es.zenomedia.com:433}
      index: ${ES_SESSIONS_INDEX:dev-zeno-streaming-sessions-*}
  media-service:
    url: ${MEDIA_SERVICE_URL:https://stream-admedia-dev.zenomedia.com}
  session-context:
    url: ${SESSION_CONTEXT_SERVICE_URL:https://stream-lc-dev.zenomedia.com/contexts}
    requests:
      timeout: 5000
  traffic-manager:
    url: ${TRAFFIC_MANAGER_SERVICE_URL:https://stream-tm-dev.zenomedia.com/actions}

local:
  external:
    ip: 127.0.0.1

keystore:
  jks: ${KEYSTORE_JKS:/home/jenkins/pki/jenkins.jks}
  cert: ${KEYSTORE_CERT:/home/jenkins/pki/jenkins-key.pem}
  key: ${KEYSTORE_KEY:/home/jenkins/pki/jenkins.pem}
  password: ${KEYSTORE_PASSWORD:Z55ByGcXytG3J13xZ7F}

ffmpeg:
  path: ${FFMPEG_PATH:/usr/bin/ffmpeg}